framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/admin-panel/build/default/manifest.json'
        packages:
            default:
                json_manifest_path: '%kernel.project_dir%/public/admin-panel/build/default/manifest.json'
            custom-entries:
                json_manifest_path: '%kernel.project_dir%/public/admin-panel/build/custom-entries/manifest.json'
            velzon-theme:
                json_manifest_path: '%kernel.project_dir%/public/admin-panel/build/velzon-theme/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/public/admin-panel/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/admin-panel/build/default'
        CustomEntries: '%kernel.project_dir%/public/admin-panel/build/custom-entries'
        VelzonTheme: '%kernel.project_dir%/public/admin-panel/build/velzon-theme'
